<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<?php echo $this->headTitle('Connexion | Admin My webtoprint')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/ressources_bo_webapp/favicon.ico'))					
						->prependStylesheet($this->basePath('ressources_bo_webapp/assets/global/plugins/uniform/css/uniform.default.css'))
                        ->prependStylesheet($this->basePath('ressources_bo_webapp/assets/global/plugins/bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('ressources_bo_webapp/assets/global/plugins/simple-line-icons/simple-line-icons.min.css'))
                        ->prependStylesheet($this->basePath('ressources_bo_webapp/assets/global/plugins/font-awesome/css/font-awesome.min.css')) ?>
<!-- END GLOBAL MANDATORY STYLES -->
<style>
body {
    background-color: #FFFFFF !important;
}
</style>
<?php echo $this->headScript()        
	        	->prependFile($this->basePath('ressources_bo_webapp/assets/global/plugins/uniform/jquery.uniform.min.js'))
	            ->prependFile($this->basePath('ressources_bo_webapp/assets/global/plugins/jquery.cokie.min.js'))
	            ->prependFile($this->basePath('ressources_bo_webapp/assets/global/plugins/jquery.blockui.min.js'))
	            ->prependFile($this->basePath('ressources_bo_webapp/assets/global/plugins/bootstrap/js/bootstrap.min.js'))
	            ->prependFile($this->basePath('ressources_bo_webapp/assets/global/plugins/jquery-migrate.min.js'))
	            ->prependFile($this->basePath('ressources_bo_webapp/assets/global/plugins/jquery.min.js'))
	        ; ?>       
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="login">
	<?php echo $this->content; ?>
<div class="copyright">
	 <?php echo date('Y') ?> © EHCG My Web Root.
</div>
<!-- END LOGIN -->
<?php echo $this->inlineScript() ?>
</body>
<!-- END BODY -->
</html>